### ISSUE TITLE
Remove outline button:focus

### ISSUE THREAD

**Issue by magsout** [cssrecipes/reset#3]
Good idea or not ?

![capture d ecran 2014-10-28 a 10 51 28](https://cloud.githubusercontent.com/assets/1997108/4806315/0757af98-5e88-11e4-883f-187709877fd1.png)

**Comment by MoOx** [comment]
Bad imo. Not good for a11y

**Comment by bloodyowl** [comment]
we should make a poll to ask users if they expect it to be removed by a reset (I personally think so) to implement it themselves for a prettier result

**Comment by MoOx** [comment]
Plz make a poll

**Comment by bloodyowl** [comment]
with what?

**Comment by MoOx** [comment]
dunno.
